export const ErrorCodes = {
  INVALID_DISPLAY_NAME: 'INVALID_DISPLAY_NAME',
  DUPLICATE_NAME: 'DUPLICATE_NAME',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_EXPIRED: 'ROOM_EXPIRED',
  ROOM_FULL: 'ROOM_FULL',
  GAME_ALREADY_STARTED: 'GAME_ALREADY_STARTED',
  CAPACITY_FULL: 'CAPACITY_FULL',
  RATE_LIMITED: 'RATE_LIMITED',
  INVALID_STATE: 'INVALID_STATE',
  INVALID_PATH: 'INVALID_PATH',
  SESSION_SUPERSEDED: 'SESSION_SUPERSEDED',
  MAINTENANCE: 'MAINTENANCE',
  DICTIONARY_UNAVAILABLE: 'DICTIONARY_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
